[workspace]

[package]
# Pseudo-package whose dependencies are imported and buckified
name = "rust-third-party"
version = "0.0.0"
publish = false
edition = "2021"

# Dummy target to keep Cargo happy
[[bin]]
name = "top"
path = "top/main.rs"

[dependencies]
anyhow = "1.0.65"
bitflags = "1.3"
bstr = { version = "1.0", features = ["std", "unicode"] }
bumpalo = { version = "3.11.1", features = ["collections"] }
clap = { version = "3.2.23", features = ["derive", "env", "regex", "unicode"] }
convert_case = "0.4.0"
derive_more = "0.99.17"
hex = "0.4.3"
indexmap = { version = "1.9.2", features = ["arbitrary", "rayon", "serde-1"] }
md-5 = "0.10"
once_cell = "1.12"
proc-macro2 = "1.0.46"
quote = "1.0"
regex = "1.6.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.136", features = ["derive", "rc"] }
syn = { version = "1.0.102", features = ["extra-traits", "fold", "full", "visit", "visit-mut"] }
synstructure = "0.12"
tempdir = "0.3.7"
thiserror = "1.0.36"
toml = "=0.5.8"
