buildscript = []

[platform_fixup.'cfg(target_os = "windows")']
# extra_deps = [
#     "fbsource//third-party/toolchains/win:advapi32.lib",
#     "fbsource//third-party/toolchains/win:bcrypt.lib",
#     "fbsource//third-party/toolchains/win:d3d11.lib",
#     "fbsource//third-party/toolchains/win:d3d12.lib",
#     "fbsource//third-party/toolchains/win:d3dcompiler.lib",
#     "fbsource//third-party/toolchains/win:dbghelp.lib",
#     "fbsource//third-party/toolchains/win:delayimp.lib",
#     "fbsource//third-party/toolchains/win:dxgi.lib",
#     "fbsource//third-party/toolchains/win:cfgmgr32.lib",
#     "fbsource//third-party/toolchains/win:ComCtl32.Lib",
#     "fbsource//third-party/toolchains/win:comdlg32.lib",
#     "fbsource//third-party/toolchains/win:crypt32.lib",
#     "fbsource//third-party/toolchains/win:dnsapi.lib",
#     "fbsource//third-party/toolchains/win:dwmapi.lib",
#     "fbsource//third-party/toolchains/win:gdi32.lib",
#     "fbsource//third-party/toolchains/win:imm32.lib",
#     "fbsource//third-party/toolchains/win:iphlpapi.lib",
#     "fbsource//third-party/toolchains/win:kernel32.lib",
#     "fbsource//third-party/toolchains/win:ksuser.lib",
#     "fbsource//third-party/toolchains/win:legacy_stdio_definitions.lib",
#     "fbsource//third-party/toolchains/win:mf.lib",
#     "fbsource//third-party/toolchains/win:mfplat.lib",
#     "fbsource//third-party/toolchains/win:mfreadwrite.lib",
#     "fbsource//third-party/toolchains/win:mfuuid.lib",
#     "fbsource//third-party/toolchains/win:mpr.lib",
#     "fbsource//third-party/toolchains/win:netapi32.lib",
#     "fbsource//third-party/toolchains/win:ole32.lib",
#     "fbsource//third-party/toolchains/win:oleaut32.lib",
#     "fbsource//third-party/toolchains/win:opengl32.lib",
#     "fbsource//third-party/toolchains/win:pathcch.lib",
#     "fbsource//third-party/toolchains/win:Pdh.lib",
#     "fbsource//third-party/toolchains/win:PowrProf.lib",
#     "fbsource//third-party/toolchains/win:Psapi.lib",
#     "fbsource//third-party/toolchains/win:qwave.lib",
#     "fbsource//third-party/toolchains/win:RpcRT4.Lib",
#     "fbsource//third-party/toolchains/win:rtworkq.lib",
#     "fbsource//third-party/toolchains/win:secur32.lib",
#     "fbsource//third-party/toolchains/win:SetupAPI.Lib",
#     "fbsource//third-party/toolchains/win:shell32.lib",
#     "fbsource//third-party/toolchains/win:strmiids.lib",
#     "fbsource//third-party/toolchains/win:shlwapi.lib",
#     "fbsource//third-party/toolchains/win:synchronization.lib",
#     "fbsource//third-party/toolchains/win:user32.lib",
#     "fbsource//third-party/toolchains/win:userenv.lib",
#     "fbsource//third-party/toolchains/win:uuid.lib",
#     "fbsource//third-party/toolchains/win:uxtheme.lib",
#     "fbsource//third-party/toolchains/win:version.lib",
#     "fbsource//third-party/toolchains/win:WindowsApp.lib",
#     "fbsource//third-party/toolchains/win:wininet.lib",
#     "fbsource//third-party/toolchains/win:winmm.lib",
#     "fbsource//third-party/toolchains/win:winspool.lib",
#     "fbsource//third-party/toolchains/win:winusb.lib",
#     "fbsource//third-party/toolchains/win:ws2_32.lib",
# ]
[[platform_fixup.'cfg(target_os = "windows")'.buildscript]]
[platform_fixup.'cfg(target_os = "windows")'.buildscript.rustc_flags]
